version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_DIAGNOSTICS_ENABLED=false
      - TELEGRAM_BOT_TOKEN=<Place your bot token here>
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped

  bot:
    build:
      context: ./bot
    ports:
      - "8000:8000"
    depends_on:
      - n8n
    restart: unless-stopped
